### ISSUE TITLE
Implementing Test Automation for Basic Functionality

### ISSUE THREAD

**Issue by JayWei1215** [JayWei1215/checkstyle#2]
### Expected Behavior

- All existing tests should be successfully moved to the new Checkstyle configuration project.
- Basic test automation should be set up using GitHub Actions to ensure continuous integration and continuous delivery (CI/CD) of the Checkstyle plugin.

### Context

Automating tests and setting up CI/CD pipelines are crucial steps to ensure the reliability and stability of the Checkstyle plugin. Without proper test automation, it would be challenging to maintain the quality of the plugin, detect regressions, or ensure that new changes do not break existing functionality. This could result in a lack of confidence among early adopters and contributors.

**Comment by oleg-nenashev** [comment]
At this stage, I would prioritize it after #10 is incorporated and the code is compilable

**Comment by oleg-nenashev** [comment]
FTR https://github.com/gradle/gradle/tree/master/platforms/jvm/code-quality/src/integTest/groovy/org/gradle/api/plugins/quality/checkstyle needs to be moved too before we consider this task completed. A good practice is using Checklists in the description for multi-item stories
